### ISSUE TITLE
Function Call功能没有返回结果，请问是什么原因

### ISSUE THREAD

**Issue by Jacky1-Jiang** [MetaGLM/zhipuai-sdk-csharp-v4#3]
![47b638cf9850627b735c56cc7b810b0](https://github.com/MetaGLM/zhipuai-sdk-csharp-v4/assets/68949216/d743cecf-9c53-46e8-bd3b-6f869c464409)

**Comment by zRzRzRzRzRzRzR** [comment]
这这调用了啊，模型并不会真正的执行工具，而是告诉你你调用的参数
